#
# Name of this configuration group.
#
across.web:
  #
  # Web has a low priority, allowing other configurations to override.
  #
  priority: 1
  #
  # List of interfaces, classes, annotations that should always be exposed.
  #
  exposed:
    - org.springframework.boot.autoconfigure.web.servlet.error.ErrorViewResolver
    - org.springframework.boot.autoconfigure.web.servlet.error.ErrorController
    - org.springframework.boot.autoconfigure.web.servlet.error.ErrorAttributes
    - org.springframework.messaging.simp.SimpMessagingTemplate
    - org.springframework.web.socket.config.annotation.WebSocketMessageBrokerConfigurer
    - org.springframework.web.socket.config.annotation.WebSocketConfigurer
    - org.thymeleaf.dialect.IDialect
    - org.thymeleaf.templateresolver.ITemplateResolver

  #
  # Auto-configuration class rules.
  #
  auto-configuration:
    com.foreach.across.autoconfigure.AcrossWebModuleAutoConfiguration: true
    org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration:
      destination: AcrossContextPostProcessorModule
    #
    # Disabled auto-configuration classes - usually because AcrossWebModule adds them manually
    #
    org.springframework.boot.autoconfigure.web.client.RestTemplateAutoConfiguration: false
    org.springframework.boot.autoconfigure.web.servlet.HttpEncodingAutoConfiguration: false
    org.springframework.boot.autoconfigure.http.HttpMessageConvertersAutoConfiguration: false
    org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration: false
    org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration: false
    org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration: false
    org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguration: false
    org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration: false
    org.springframework.boot.autoconfigure.websocket.servlet.WebSocketMessagingAutoConfiguration: false
  #
  # Ensure Spring MVC is not configured manually.
  #
  illegal-configurations:
    # Web MVC
    spring-webmvc:
      configuration:
        org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport:
          allowed: AcrossContextPostProcessorModule
      description: This is usually due to the use of @EnableWebMvc on the application configuration, which is not compatible with Across applications.
      action: Remove the use of @EnableWebMvc or WebMvcConfigurationSupport from the application configuration or custom module. Use AcrossWebModule instead and only provide WebMvcConfigurer classes for additional configuration.
    # Web-sockets
    spring-websocket:
      configuration:
        org.springframework.web.socket.config.annotation.WebSocketConfigurationSupport:
          allowed: AcrossContextPostProcessorModule
        org.springframework.web.socket.config.annotation.WebSocketMessageBrokerConfigurationSupport:
          allowed: AcrossContextPostProcessorModule
      description: This is usually due to the use of @EnableWebSocket or @EnableWebSocketMessageBroker on the application configuration, which is not compatible with Across applications.
      action: Remove the use of @EnableWebSocket or @EnableWebSocketMessageBroker. Web socket support is activated automatically by AcrossWebModule if the right dependencies are on the classpath and configurer beans are present.